### PR TITLE
LUA-1187 sieve_rule translate fix

### PR DESCRIPTION
**Pull request by DrakaGytis**

### CODE REVIEW

**Comment by robert-zenedge** [comment]
Hey @DrakaGytis, have a look at https://github.com/p0pr0ck5/lua-resty-waf/commit/b3b0a6dd63181cd9b321671cadf830800533025f, I think this might be a better approach? We don't need to create a new string object, just bypass it if it's _not_ a string. Thoughts?

**Comment by DrakaGytis** [comment]
Hi @robert-zenedge, that is much better approach, what about `type(collection) = "number"` or only strings can be looked up?

**Comment by robert-zenedge** [comment]
I think it only makes sense for strings to be transformed. The only way a collection would be a number type is if the `#` operator was used in the collection definition? I'm can't think of any cases where we would want to transform it. And query values like query params, headers, etc, are always string values even if they are numeric (some specific request values like `ngx.var.http_content_length` are number types, but we don't use these directly). Thoughts?

As for the sieve fixes, would you like to PR these upstream? Would love to have this fix in place :)

**Comment by DrakaGytis** [comment]
@robert-zenedge I will push this to upstream. And update this one.

**Comment by DrakaGytis** [comment]
Merged directly to master without LUA tags.

**Pull request closed without merging**
